BOARD_TAG = mega2560
MONITOR_PORT = /dev/ttyACM0

ARDMK_DIR   = /home/roevhat/apps/arduino-mk
ARDUINO_DIR = /usr/local/share/arduino

USER_LIB_PATH = lib

AVR_TOOLS_DIR=/usr

include /home/roevhat/apps/arduino-mk/Arduino.mk