BOARD_TAG = mega2560
MONITOR_PORT = /dev/ttyACM0

#PROJECT_DIR = /home/snemanden/Dropbox/MJC/MJC\ 2014/main/src
USER_LIB_PATH := $(PROJECT_DIR)/lib

AVR_TOOLS_DIR=/usr

ARDMK_DIR = /home/snemanden

include /home/snemanden/Arduino.mk
